# Generated by Django 2.2.17 on 2021-01-18 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommenditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='ブランド名')),
                ('product', models.CharField(max_length=100, verbose_name='製品名')),
                ('content', models.TextField(verbose_name='説明')),
                ('image', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('price', models.CharField(max_length=100, verbose_name='本体価格')),
                ('acne_point', models.IntegerField(default=0, verbose_name='ニキビポイント')),
                ('pores_point', models.IntegerField(default=0, verbose_name='毛穴ポイント')),
                ('berd_point', models.IntegerField(default=0, verbose_name='髭剃り負けポインント')),
                ('wrinkle_point', models.IntegerField(default=0, verbose_name='シワポイント')),
                ('official_page', models.URLField(verbose_name='公式URL')),
                ('rakuten_page', models.URLField(verbose_name='楽天URL')),
                ('amazon_page', models.URLField(verbose_name='アマゾンURL')),
                ('trouble_name1', models.CharField(blank=True, max_length=100, verbose_name='ニキビ')),
                ('trouble_name2', models.CharField(blank=True, max_length=100, verbose_name='毛穴')),
                ('trouble_name3', models.CharField(blank=True, max_length=100, verbose_name='髭剃り負け')),
                ('trouble_name4', models.CharField(blank=True, max_length=100, verbose_name='シワ')),
                ('capacity', models.CharField(max_length=100, verbose_name='容量')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosme.Category')),
                ('price_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosme.Price')),
                ('skintype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosme.SkinType')),
            ],
        ),
    ]
